# Generated by Django 4.0.3 on 2023-01-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_userfollowing'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='banner_url_image',
            field=models.URLField(default='https://media.istockphoto.com/id/1260122654/photo/autumn-landscape-beautiful-city-park-with-fallen-yellow-leaves.jpg?s=612x612&w=0&k=20&c=EVuX7Mp6nqzHaGijUPS98KpNsF6j_6Q4-vhmY9x8U-0=', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='photo_url_image',
            field=models.URLField(default='https://ichef.bbci.co.uk/news/660/cpsprodpb/48DD/production/_107435681_perro1.jpg', max_length=500),
        ),
    ]
